"""Initial schema: markets, orders, trades, positions, sentiment_scores, whale_alerts

Revision ID: 69800290244a
Revises: 
Create Date: 2026-01-05 19:53:28.381297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69800290244a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('markets',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('yes_price', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('no_price', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('volume_24h', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('liquidity', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('related_asset', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_markets_asset', 'markets', ['related_asset'], unique=False)
    op.create_index('idx_markets_created', 'markets', ['created_at'], unique=False)
    op.create_index('idx_markets_end_date', 'markets', ['end_date'], unique=False)
    op.create_table('sentiment_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('asset', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('price_component', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('news_component', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('social_component', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('volume_component', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('timeframe', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sentiment_asset', 'sentiment_scores', ['asset'], unique=False)
    op.create_index('idx_sentiment_asset_timestamp', 'sentiment_scores', ['asset', 'timestamp'], unique=False)
    op.create_index('idx_sentiment_timestamp', 'sentiment_scores', ['timestamp'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('market_id', sa.String(length=255), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('size', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('filled_size', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('average_fill_price', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('strategy', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('sentiment_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_orders_created', 'orders', ['created_at'], unique=False)
    op.create_index('idx_orders_market', 'orders', ['market_id'], unique=False)
    op.create_index('idx_orders_status', 'orders', ['status'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('market_id', sa.String(length=255), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('size', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('unrealized_pnl', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('strategy', sa.String(length=50), nullable=False),
    sa.Column('entry_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('entry_sentiment', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_positions_market', 'positions', ['market_id'], unique=False)
    op.create_index('idx_positions_open', 'positions', ['is_open'], unique=False)
    op.create_index('idx_positions_opened', 'positions', ['opened_at'], unique=False)
    op.create_table('whale_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('market_id', sa.String(length=255), nullable=False),
    sa.Column('wallet_address', sa.String(length=255), nullable=False),
    sa.Column('order_size', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('relative_size', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('expected_impact_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('action_taken', sa.String(length=100), nullable=True),
    sa.Column('frontrun_order_id', sa.String(length=255), nullable=True),
    sa.Column('frontrun_success', sa.Boolean(), nullable=True),
    sa.Column('detection_latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_whale_detected', 'whale_alerts', ['detected_at'], unique=False)
    op.create_index('idx_whale_market', 'whale_alerts', ['market_id'], unique=False)
    op.create_index('idx_whale_wallet', 'whale_alerts', ['wallet_address'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('order_id', sa.String(length=255), nullable=False),
    sa.Column('market_id', sa.String(length=255), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('size', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('fee', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('pnl', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('strategy', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('sentiment_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_trades_executed', 'trades', ['executed_at'], unique=False)
    op.create_index('idx_trades_market', 'trades', ['market_id'], unique=False)
    op.create_index('idx_trades_strategy', 'trades', ['strategy'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_trades_strategy', table_name='trades')
    op.drop_index('idx_trades_market', table_name='trades')
    op.drop_index('idx_trades_executed', table_name='trades')
    op.drop_table('trades')
    op.drop_index('idx_whale_wallet', table_name='whale_alerts')
    op.drop_index('idx_whale_market', table_name='whale_alerts')
    op.drop_index('idx_whale_detected', table_name='whale_alerts')
    op.drop_table('whale_alerts')
    op.drop_index('idx_positions_opened', table_name='positions')
    op.drop_index('idx_positions_open', table_name='positions')
    op.drop_index('idx_positions_market', table_name='positions')
    op.drop_table('positions')
    op.drop_index('idx_orders_status', table_name='orders')
    op.drop_index('idx_orders_market', table_name='orders')
    op.drop_index('idx_orders_created', table_name='orders')
    op.drop_table('orders')
    op.drop_index('idx_sentiment_timestamp', table_name='sentiment_scores')
    op.drop_index('idx_sentiment_asset_timestamp', table_name='sentiment_scores')
    op.drop_index('idx_sentiment_asset', table_name='sentiment_scores')
    op.drop_table('sentiment_scores')
    op.drop_index('idx_markets_end_date', table_name='markets')
    op.drop_index('idx_markets_created', table_name='markets')
    op.drop_index('idx_markets_asset', table_name='markets')
    op.drop_table('markets')
    # ### end Alembic commands ###
